spring.application.name=restaurante

# POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurante
spring.datasource.username=postgres
spring.datasource.password=luan

# DRIVER
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update

# MOSTRAR SQL NO CONSOLE
spring.jpa.show-sql=true

# FORMATAR SQL
spring.jpa.properties.hibernate.format_sql=true

# DIALETO POSTGRES
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect